-- AlterTable
ALTER TABLE "SiteContent" ADD COLUMN     "aboutHeroText" TEXT NOT NULL DEFAULT 'Biostore est née d''une conviction simple : bien manger ne devrait jamais être un compromis. Depuis 2021, nous transformons des produits bruts gabonais en essentiels du quotidien, sans superflu et avec exigence.',
ADD COLUMN     "aboutHeroTitle" TEXT NOT NULL DEFAULT 'Le naturel, avec intention.',
ADD COLUMN     "commitment1Text" TEXT NOT NULL DEFAULT 'Nous travaillons main dans la main avec des producteurs gabonais pour valoriser des matières premières locales.',
ADD COLUMN     "commitment1Title" TEXT NOT NULL DEFAULT 'Des filières locales',
ADD COLUMN     "commitment2Text" TEXT NOT NULL DEFAULT 'Chaque lot est préparé en petite quantité, dans le respect des bonnes pratiques d''hygiène et de traçabilité.',
ADD COLUMN     "commitment2Title" TEXT NOT NULL DEFAULT 'Une transformation soignée',
ADD COLUMN     "commitment3Text" TEXT NOT NULL DEFAULT 'Une partie de notre activité soutient la formation de jeunes transformateurs locaux, pour faire grandir le savoir-faire.',
ADD COLUMN     "commitment3Title" TEXT NOT NULL DEFAULT 'Un impact communautaire',
ADD COLUMN     "founderName" TEXT NOT NULL DEFAULT 'Aïcha Ndong',
ADD COLUMN     "founderPhoto" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=900&q=85',
ADD COLUMN     "founderQuote" TEXT NOT NULL DEFAULT 'Biostore est parti d''un constat tout simple : dans nos marchés, il était devenu difficile de trouver des produits vraiment naturels, sans additifs ni promesses vides. J''ai voulu créer une marque honnête, qui transforme avec soin ce que notre terre gabonaise nous offre déjà généreusement.',
ADD COLUMN     "founderRole" TEXT NOT NULL DEFAULT 'Fondatrice & directrice, Biostore',
ADD COLUMN     "founderText" TEXT NOT NULL DEFAULT 'Chaque produit qui sort de notre atelier porte cette exigence : peu d''ingrédients, mais les bons, et un respect total du consommateur. Ce n''est pas seulement une entreprise que nous construisons, c''est une manière de redonner confiance dans ce que l''on mange.',
ADD COLUMN     "missionImage" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=1100&q=85',
ADD COLUMN     "missionQuote" TEXT NOT NULL DEFAULT 'Le naturel n''est pas une tendance. C''est un engagement de tous les jours.',
ADD COLUMN     "missionText1" TEXT NOT NULL DEFAULT 'Nous croyons qu''une alimentation saine ne doit pas être un luxe réservé à quelques-uns. Notre mission est de rendre les produits naturels gabonais accessibles, abordables et présents dans chaque foyer, tout en soutenant une chaîne de production locale, courte et respectueuse.',
ADD COLUMN     "missionText2" TEXT NOT NULL DEFAULT 'Pas d''additifs, pas de raccourcis : chaque produit qui porte notre nom est préparé avec la même rigueur que le tout premier pot de miel vendu en 2021.',
ADD COLUMN     "missionTitle" TEXT NOT NULL DEFAULT 'Rendre le naturel accessible.';
